### ISSUE TITLE
Function to import/export notes to txt files not described

### ISSUE THREAD

**Issue by davidhedlund** [alaskalinuxuser/app_justnotes#4]
I suggest that you change the short description from "Take notes" "Take notes, and import/export them to txt files."

The txt import/export feature should at least be mentioned in the full description.

What do you think?

**Comment by alaskalinuxuser** [comment]
Thanks David. Yes, I suppose that would make it clearer to the users. Are you coming from F-droid or the play store? I am very new at app making, so I am still learning new things. As I learn, I've been upgrading the app. So that feature did not originally exist. I'm not quite sure how to change that on F-droid.

As always, feedback is always appreciated!

**Comment by davidhedlund** [comment]
@alaskalinuxuser Oh sorry, I should have submit this issue in https://gitlab.com/fdroid/fdroiddata/issues

But you can do that, just submit a new Issue, preferably the title start with "Just Notes: <your short description>"

Example: https://gitlab.com/fdroid/fdroiddata/issues/687

**Comment by alaskalinuxuser** [comment]
No worries, I read a very helpful pointer in their documentation. I have updated it in a merge request:
https://gitlab.com/fdroid/fdroiddata/merge_requests/2175

Thanks again for taking the time to look at my app and caring enough to make a comment! I really appreciate it!

**Comment by davidhedlund** [comment]
@alaskalinuxuser Thank you too.
