### ISSUE TITLE
Stop using pre-release libraries

### ISSUE THREAD

**Issue by ghost** [alaskalinuxuser/app_justnotes#6]
You use constraint-layout in an alpha version, is there a reason not to switch to an official released library version?

**Comment by alaskalinuxuser** [comment]
Great point. I updated my Android Studio to 2.3, and it "helped" me by putting the costraint layout in, which I was not even using before. I updated the github not realizing the change. I already ran into that problem with several of my apps and am trying to fix them. I will remove it, since I don't plan to use it.

**Comment by alaskalinuxuser** [comment]
Fixed in commit: https://github.com/alaskalinuxuser/app_justnotes/commit/9162b2bb87c46574765ced7b4a7f9b8ff223756f

@krt16s 

Thanks for pointing that out. And I appreciate all of your hard work on F-Droid! Love the new F-Droid layout!
